version: '3.7'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-8.1.0}
    volumes:
      - ./:/var/www/app
      - /var/www/app/vendor
    extra_hosts:
      - "internal.host:host-gateway"
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./:/var/www/app:cached
    restart: on-failure
    depends_on:
      - app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
